import type { Locale } from "@/lib/i18n";

const en = {
  heroEyebrow: "Community guesses",
  heroTitle: "When does Chapter 421 drop?",
  previewLabel: "Local preview · no real votes",
    previewFriend: "Try as a friend",
  nicknameLabel: "Nickname",
  verdictNamed: "{name}'s guess",
  verdictUnnamed: "Your guess",
  title: "Chapter 421: your prediction",
  intro: "Predict the return. No account needed.",
  pickDate: "Pick a date",
  voteReveal: "Lock my date & see the guesses",
  finalShort: "Your date is final. Entries close at the official announcement.",  retry: "Try again",
  moreOptions: "Friends & reminders",
  monthOverview: "Guesses by month",
  verificationHelp: "Verification unavailable. Reload to try again.",  home: "When do you think Chapter 421 will arrive?",
  guessesSoFar: "Guesses so far",
  chooseDate: "No date picked yet",
  distributionTitle: "Guesses by day",
  date: "Your predicted publication date in Japan",
  groupDate: "Predicted date",
  fanGuess: "A fan prediction, separate from official announcements and the site's forecast.",
  publicHint: "Your nickname and date may be public.",
  unlockHint: "Publication in Japan · Fan guesses",
  unlockHintNoEmail: "Vote to reveal the community's picks. Sharing and challenges are optional; email updates are unavailable right now.",
  savedHelp: "Your date is saved. Compare it with the community below.",
  communityNote: "These are fans' chosen dates.",
  firstPick: "No guesses yet.",
  comparison: "{percent} of players picked a later date than you.",
  statsDetails: "More community statistics",
  resultsLoading: "Loading the community's picks…",
  resultsError: "Your date is saved, but community picks couldn't load. Try again.",
  nextSteps: "Share, challenge or stay updated",
  optionalSteps: "Choose any or all of these. Your prediction is already saved.",
  shareHelp: "Share your date with a card, or copy a link inviting others to make their own pick.",
  challengeHelp: "Invite friends to a shared table of predictions. The closest date wins after publication.",
  createChallenge: "Create a friend challenge",
  copyChallenge: "Copy challenge link",
  emailTitle: "Get results by email",
  emailAdd: "Notify me",
  emailHelp: "Optional. Confirm your address to receive your result when the chapter is published.",
  emailUnavailable: "Email delivery is currently unavailable.",
    emailAnnouncement: "Leave your email to receive the official announcement.",
  recovery: "Keep access to your prediction",
  recoveryHelp: "This browser remembers your date. Save a private link to open it on another device.",
  restore: "Keep this link private: anyone with it can access your prediction.",
};

export const gameFlowCopy: Record<Locale, typeof en> = {
  en,
  fr: {
    heroEyebrow: "Pronostics de la communauté",
    heroTitle: "Quand sortira le chapitre 421 ?",
    previewLabel: "Aperçu local · aucun vote réel",
    previewFriend: "Tester un ami",
    nicknameLabel: "Pseudo",
    verdictNamed: "Le pronostic de {name}",
    verdictUnnamed: "Votre pronostic",
    title: "Chapitre 421 : votre pronostic",
    intro: "Pronostiquez le retour. Sans inscription.",
    pickDate: "Choisir une date",
    voteReveal: "Valider ma date et voir les pronostics",
    finalShort: "Votre date est définitive. Les votes ferment à l’annonce officielle.",    retry: "Réessayer",
    moreOptions: "Amis et rappels",
    monthOverview: "Pronostics par mois",
    verificationHelp: "Vérification indisponible. Rechargez pour réessayer.",    home: "À votre avis, quand sortira le chapitre 421 ?",
    guessesSoFar: "Pronostics à ce jour",
    chooseDate: "Aucune date choisie",
    distributionTitle: "Pronostics par jour",
    date: "Votre date de publication prévue au Japon",
    groupDate: "Date prévue",
    fanGuess: "Un pronostic de fan, distinct des annonces officielles et des prévisions du site.",
    publicHint: "Votre pseudo et votre date peuvent être publics.",
    unlockHint: "Publication au Japon · Pronostics de fans",
    unlockHintNoEmail: "Votez pour découvrir les choix de la communauté. Le partage et les défis sont facultatifs ; les emails sont indisponibles pour le moment.",
    savedHelp: "Votre date est enregistrée. Comparez-la aux choix de la communauté ci-dessous.",
    communityNote: "Ce sont les dates choisies par les fans.",
    firstPick: "Aucun pronostic pour le moment.",
    comparison: "{percent} des joueurs ont choisi une date plus tardive que la vôtre.",
    statsDetails: "Plus de statistiques communautaires",
    resultsLoading: "Chargement des choix de la communauté…",
    resultsError: "Votre date est enregistrée, mais les choix de la communauté n’ont pas pu être chargés. Réessayez.",
    nextSteps: "Partager, défier ou rester informé",
    optionalSteps: "Choisissez une ou plusieurs options. Votre pronostic est déjà enregistré.",
    shareHelp: "Partagez votre date sur une carte ou copiez un lien pour inviter d’autres fans à faire leur pronostic.",
    challengeHelp: "Invitez vos amis à comparer leurs pronostics dans un tableau commun. La date la plus proche gagne après publication.",
    createChallenge: "Créer un défi entre amis",
    copyChallenge: "Copier le lien du défi",
    emailTitle: "Recevoir les résultats par email",
    emailAdd: "Me prévenir",
    emailHelp: "Facultatif. Confirmez votre adresse pour recevoir votre résultat à la publication du chapitre.",
    emailUnavailable: "L’envoi d’emails est indisponible pour le moment.",
    emailAnnouncement: "Laissez votre email pour recevoir l’annonce officielle.",
    recovery: "Retrouver votre pronostic",
    recoveryHelp: "Ce navigateur mémorise votre date. Conservez un lien privé pour la retrouver sur un autre appareil.",
    restore: "Gardez ce lien privé : toute personne qui le possède peut accéder à votre pronostic.",
  },
  es: {
    heroEyebrow: "Pronósticos de la comunidad",
    heroTitle: "¿Cuándo sale el capítulo 421?",
    previewLabel: "Vista previa local · sin votos reales",
    previewFriend: "Probar como amigo",
    nicknameLabel: "Apodo",
    verdictNamed: "El pronóstico de {name}",
    verdictUnnamed: "Tu pronóstico",
    title: "Capítulo 421: tu pronóstico",
    intro: "Predice el regreso. Sin cuenta.",
    pickDate: "Elige una fecha",
    voteReveal: "Confirmar mi fecha y ver los pronósticos",
    finalShort: "Tu fecha es definitiva. Las inscripciones cierran con el anuncio oficial.",    retry: "Intentar de nuevo",
    moreOptions: "Amigos y recordatorios",
    monthOverview: "Pronósticos por mes",
    verificationHelp: "Verificación no disponible. Recarga para reintentar.",    home: "¿Cuándo crees que llegará el capítulo 421?",
    guessesSoFar: "Pronósticos hasta ahora",
    chooseDate: "Aún no has elegido una fecha",
    distributionTitle: "Pronósticos por día",
    date: "Tu fecha prevista de publicación en Japón",
    groupDate: "Fecha prevista",
    fanGuess: "Un pronóstico de fan, independiente de los anuncios oficiales y de la previsión del sitio.",
    publicHint: "Tu apodo y tu fecha pueden ser públicos.",
    unlockHint: "Publicación en Japón · Pronósticos de fans",
    unlockHintNoEmail: "Vota para ver las fechas de la comunidad. Compartir y participar en retos es opcional; el correo no está disponible ahora.",
    savedHelp: "Tu fecha está guardada. Compárala con las de la comunidad abajo.",
    communityNote: "Son fechas elegidas por fans.",
    firstPick: "Aún no hay pronósticos.",
    comparison: "El {percent} de los jugadores eligió una fecha posterior a la tuya.",
    statsDetails: "Más estadísticas de la comunidad",
    resultsLoading: "Cargando las fechas de la comunidad…",
    resultsError: "Tu fecha está guardada, pero no se pudieron cargar las de la comunidad. Inténtalo de nuevo.",
    nextSteps: "Comparte, reta o recibe novedades",
    optionalSteps: "Elige una o todas las opciones. Tu pronóstico ya está guardado.",
    shareHelp: "Comparte tu fecha en una tarjeta o copia un enlace para invitar a otros a hacer su pronóstico.",
    challengeHelp: "Invita a tus amigos a una tabla compartida de pronósticos. La fecha más cercana gana tras la publicación.",
    createChallenge: "Crear un reto entre amigos",
    copyChallenge: "Copiar enlace del reto",
    emailTitle: "Recibir resultados por correo",
    emailAdd: "Avisarme",
    emailHelp: "Opcional. Confirma tu correo para recibir tu resultado cuando se publique el capítulo.",
    emailUnavailable: "El envío de correos no está disponible por ahora.",
    emailAnnouncement: "Deja tu correo para recibir el anuncio oficial.",
    recovery: "Conserva el acceso a tu pronóstico",
    recoveryHelp: "Este navegador recuerda tu fecha. Guarda un enlace privado para abrirla en otro dispositivo.",
    restore: "No compartas este enlace: quien lo tenga podrá acceder a tu pronóstico.",
  },
  pt: {
    heroEyebrow: "Palpites da comunidade",
    heroTitle: "Quando sai o capítulo 421?",
    previewLabel: "Prévia local · sem votos reais",
    previewFriend: "Testar como amigo",
    nicknameLabel: "Apelido",
    verdictNamed: "Palpite de {name}",
    verdictUnnamed: "Seu palpite",
    title: "Capítulo 421: seu palpite",
    intro: "Dê seu palpite para a volta. Sem cadastro.",
    pickDate: "Escolha uma data",
    voteReveal: "Confirmar minha data e ver os palpites",
    finalShort: "Sua data é definitiva. As inscrições encerram no anúncio oficial.",    retry: "Tentar novamente",
    moreOptions: "Amigos e lembretes",
    monthOverview: "Palpites por mês",
    verificationHelp: "Verificação indisponível. Recarregue para tentar novamente.",    home: "Quando você acha que o capítulo 421 vai chegar?",
    guessesSoFar: "Palpites até agora",
    chooseDate: "Nenhuma data escolhida",
    distributionTitle: "Palpites por dia",
    date: "Sua previsão de data de publicação no Japão",
    groupDate: "Data prevista",
    fanGuess: "Um palpite de fã, separado dos anúncios oficiais e da previsão do site.",
    publicHint: "Seu apelido e sua data podem ser públicos.",
    unlockHint: "Publicação no Japão · Palpites de fãs",
    unlockHintNoEmail: "Vote para ver as datas da comunidade. Compartilhar e participar de desafios é opcional; os emails estão indisponíveis no momento.",
    savedHelp: "Sua data está salva. Compare com as escolhas da comunidade abaixo.",
    communityNote: "Estas são datas escolhidas por fãs.",
    firstPick: "Ainda não há palpites.",
    comparison: "{percent} dos jogadores escolheram uma data posterior à sua.",
    statsDetails: "Mais estatísticas da comunidade",
    resultsLoading: "Carregando as escolhas da comunidade…",
    resultsError: "Sua data está salva, mas não foi possível carregar as escolhas da comunidade. Tente novamente.",
    nextSteps: "Compartilhe, desafie ou acompanhe",
    optionalSteps: "Escolha uma ou todas as opções. Seu palpite já está salvo.",
    shareHelp: "Compartilhe sua data em um cartão ou copie um link para convidar outras pessoas a dar seu palpite.",
    challengeHelp: "Convide amigos para uma tabela compartilhada de palpites. A data mais próxima vence após a publicação.",
    createChallenge: "Criar um desafio entre amigos",
    copyChallenge: "Copiar link do desafio",
    emailTitle: "Receber resultados por email",
    emailAdd: "Avise-me",
    emailHelp: "Opcional. Confirme seu email para receber seu resultado quando o capítulo for publicado.",
    emailUnavailable: "O envio de emails está indisponível no momento.",
    emailAnnouncement: "Deixe seu email para receber o anúncio oficial.",
    recovery: "Mantenha o acesso ao seu palpite",
    recoveryHelp: "Este navegador lembra sua data. Salve um link privado para abri-la em outro dispositivo.",
    restore: "Mantenha este link privado: quem o tiver poderá acessar seu palpite.",
  },
  ja: {
    heroEyebrow: "みんなの予想",
    heroTitle: "第421話はいつ読める？",
    previewLabel: "ローカルプレビュー · 実際の投票には反映されません",
    previewFriend: "友達として試す",
    nicknameLabel: "ニックネーム",
    verdictNamed: "{name}さんの予想",
    verdictUnnamed: "あなたの予想",
    title: "第421話：あなたの予想",
    intro: "再開日を予想しよう。登録不要。",
    pickDate: "日付を選ぶ",
    voteReveal: "日付を確定してみんなの予想を見る",
    finalShort: "確定後の日付は変更できません。公式発表時に受付終了。",    retry: "再試行",
    moreOptions: "友達・通知",
    monthOverview: "月別の予想",
    verificationHelp: "認証を利用できません。再読み込みしてお試しください。",    home: "第421話はいつ読めると思いますか？",
    guessesSoFar: "これまでの予想数",
    chooseDate: "日付はまだ選択されていません",
    distributionTitle: "日別の予想数",
    date: "あなたが予想する日本での掲載日",
    groupDate: "予想日",
    fanGuess: "ファンの予想です。公式発表や当サイトの予測とは別のものです。",
    publicHint: "ニックネームと日付は公開される場合があります。",
    unlockHint: "日本での掲載日 · ファンの予想",
    unlockHintNoEmail: "投票すると、みんなの予想が見られます。共有と対戦は任意です。メール通知は現在利用できません。",
    savedHelp: "日付を保存しました。下のみんなの予想と比べてみましょう。",
    communityNote: "ファンが選んだ日付です。",
    firstPick: "まだ予想がありません。",
    comparison: "参加者の{percent}が、あなたより遅い日付を選びました。",
    statsDetails: "みんなの予想の詳しい統計",
    resultsLoading: "みんなの予想を読み込み中…",
    resultsError: "日付は保存されていますが、みんなの予想を読み込めませんでした。再試行してください。",
    nextSteps: "共有・友達との対戦・メール通知",
    optionalSteps: "どれでも、すべてでも利用できます。予想はすでに保存されています。",
    shareHelp: "日付をカードで共有するか、リンクをコピーしてほかの人を予想に招待できます。",
    challengeHelp: "友達を共通の予想一覧に招待しましょう。掲載後、最も近い日付の人が勝者になります。",
    createChallenge: "友達との対戦を作成",
    copyChallenge: "対戦リンクをコピー",
    emailTitle: "結果をメールで受け取る",
    emailAdd: "通知を受け取る",
    emailHelp: "任意です。メールアドレスを確認すると、掲載時に結果を受け取れます。",
    emailUnavailable: "現在メール送信は利用できません。",
    emailAnnouncement: "公式発表をメールで受け取るには、アドレスを入力してください。",
    recovery: "予想に再びアクセスするには",
    recoveryHelp: "このブラウザーは日付を記憶しています。別の端末でも開けるよう、非公開リンクを保存してください。",
    restore: "このリンクは秘密にしてください。リンクを持つ人はあなたの予想にアクセスできます。",
  },
  zh: {
    heroEyebrow: "社区预测",
    heroTitle: "第421话什么时候更新？",
    previewLabel: "本地预览 · 不计入真实投票",
    previewFriend: "模拟好友加入",
    nicknameLabel: "昵称",
    verdictNamed: "{name}的预测",
    verdictUnnamed: "你的预测",
    title: "第421话：你的预测",
    intro: "猜猜回归日期。无需注册。",
    pickDate: "选择日期",
    voteReveal: "确认日期，查看大家的预测",
    finalShort: "日期确认后不可更改。官方公告发布时截止参与。",    retry: "重试",
    moreOptions: "好友与提醒",
    monthOverview: "每月预测数",
    verificationHelp: "验证暂不可用。请刷新重试。",    home: "你觉得第421话什么时候能读到？",
    guessesSoFar: "目前的预测数",
    chooseDate: "尚未选择日期",
    distributionTitle: "每日预测数",
    date: "你预测的日本刊载日期",
    groupDate: "预测日期",
    fanGuess: "这是粉丝预测，与官方公告和本站的模型预测分开。",
    publicHint: "你的昵称和日期可能会公开。",
    unlockHint: "日本刊载日期 · 粉丝预测",
    unlockHintNoEmail: "投票后即可查看大家的预测。分享和好友挑战均为可选；邮件通知暂不可用。",
    savedHelp: "你的日期已保存。可在下方与大家的预测比较。",
    communityNote: "这些是粉丝选择的日期。",
    firstPick: "暂时还没有预测。",
    comparison: "{percent}的参与者选择了比你更晚的日期。",
    statsDetails: "更多社区统计",
    resultsLoading: "正在加载大家的预测…",
    resultsError: "你的日期已保存，但无法加载大家的预测。请重试。",
    nextSteps: "分享、挑战好友或接收通知",
    optionalSteps: "可任选一项或全部使用。你的预测已经保存。",
    shareHelp: "用卡片分享你的日期，或复制链接邀请他人参与预测。",
    challengeHelp: "邀请好友加入共同的预测列表。刊载后，日期最接近的人获胜。",
    createChallenge: "创建好友挑战",
    copyChallenge: "复制挑战链接",
    emailTitle: "通过邮件接收结果",
    emailAdd: "接收通知",
    emailHelp: "可选。确认邮箱后，将在章节刊载时收到你的结果。",
    emailUnavailable: "邮件发送暂不可用。",
    emailAnnouncement: "留下邮箱，接收官方公告。",
    recovery: "保留预测的访问方式",
    recoveryHelp: "此浏览器会记住你的日期。保存私人链接即可在其他设备上打开。",
    restore: "请勿公开此链接：持有链接的人可以访问你的预测。",
  },
  ar: {
    heroEyebrow: "توقعات المجتمع",
    heroTitle: "متى يصدر الفصل 421؟",
    previewLabel: "معاينة محلية · لا تُحتسب أصوات حقيقية",
    previewFriend: "التجربة كصديق",
    nicknameLabel: "الاسم المستعار",
    verdictNamed: "توقع {name}",
    verdictUnnamed: "توقعك",
    title: "الفصل 421: توقعك",
    intro: "توقّع موعد العودة. لا حاجة إلى حساب.",
    pickDate: "اختر تاريخًا",
    voteReveal: "ثبّت تاريخي وشاهد التوقعات",
    finalShort: "تاريخك نهائي. تُغلق المشاركة عند الإعلان الرسمي.",    retry: "حاول مجددًا",
    moreOptions: "الأصدقاء والتذكيرات",
    monthOverview: "التوقعات حسب الشهر",
    verificationHelp: "التحقق غير متاح. أعد تحميل الصفحة للمحاولة مجددًا.",    home: "متى تتوقع صدور الفصل 421؟",
    guessesSoFar: "عدد التوقعات حتى الآن",
    chooseDate: "لم تختر تاريخًا بعد",
    distributionTitle: "التوقعات حسب اليوم",
    date: "تاريخ النشر الذي تتوقعه في اليابان",
    groupDate: "التاريخ المتوقع",
    fanGuess: "توقع من أحد المعجبين، منفصل عن الإعلانات الرسمية وتوقعات الموقع.",
    publicHint: "قد يظهر اسمك المستعار وتاريخك علنًا.",
    unlockHint: "النشر في اليابان · توقعات المعجبين",
    unlockHintNoEmail: "صوّت لتشاهد توقعات المجتمع. المشاركة والتحديات اختياريتان؛ إشعارات البريد غير متاحة حاليًا.",
    savedHelp: "تم حفظ تاريخك. قارنه بتوقعات المجتمع أدناه.",
    communityNote: "هذه تواريخ اختارها المعجبون.",
    firstPick: "لا توجد توقعات بعد.",
    comparison: "اختار {percent} من المشاركين تاريخًا بعد تاريخك.",
    statsDetails: "المزيد من إحصاءات المجتمع",
    resultsLoading: "جارٍ تحميل توقعات المجتمع…",
    resultsError: "تم حفظ تاريخك، لكن تعذر تحميل توقعات المجتمع. حاول مجددًا.",
    nextSteps: "شارك أو تحدَّ أصدقاءك أو تابع النتائج",
    optionalSteps: "اختر أيًا من هذه الخيارات أو كلها. توقعك محفوظ بالفعل.",
    shareHelp: "شارك تاريخك في بطاقة أو انسخ رابطًا لدعوة الآخرين إلى توقع موعدهم.",
    challengeHelp: "ادعُ أصدقاءك إلى جدول توقعات مشترك. يفوز صاحب التاريخ الأقرب بعد النشر.",
    createChallenge: "إنشاء تحدٍّ للأصدقاء",
    copyChallenge: "نسخ رابط التحدي",
    emailTitle: "استلام النتائج بالبريد",
    emailAdd: "أبلغني",
    emailHelp: "اختياري. أكّد عنوانك لاستلام نتيجتك عند نشر الفصل.",
    emailUnavailable: "إرسال البريد غير متاح حاليًا.",
    emailAnnouncement: "أضف بريدك الإلكتروني لتصلك أخبار الإعلان الرسمي.",
    recovery: "احتفظ بإمكانية الوصول إلى توقعك",
    recoveryHelp: "يتذكر هذا المتصفح تاريخك. احفظ رابطًا خاصًا لفتحه على جهاز آخر.",
    restore: "احتفظ بهذا الرابط سرًا؛ يمكن لأي شخص يملكه الوصول إلى توقعك.",
  },
};
