import type { Locale } from "@/lib/i18n";
import { gameFlowCopy } from "./game-flow-copy";

const en = {
  email: "Email (optional)", emailHint: "Receive your result when the chapter comes out.", emailAdd: "Email me my prediction", emailPending: "Check your inbox to confirm your address.", emailConfirmed: "Email confirmed. You’ll receive the results after publication.", emailConfirm: "Confirm my email", emailConfirmTitle: "Receive the results by email", emailUnsubscribe: "Unsubscribe", emailUnsubscribeTitle: "Stop results emails", emailUnsubscribed: "You won’t receive results emails.", emailFailed: "Your prediction is saved, but the email could not be queued.", email_link_invalid: "This email link is invalid or has expired.", invalid_email: "Enter a valid email address.", winners: "The 10 closest predictions",

  title: "Your prediction", intro: "When will the next Hunter × Hunter chapter come out? Pick a day and challenge your friends. No account needed.",
  chapter: "Chapter", date: "Official publication date in Japan", nickname: "Public nickname",
  rule: "Pick a date. Entries close when the official date is announced.",
  final: "I understand that my date cannot be changed.", vote: "Lock in my date", loading: "Loading…", busy: "Saving…",
  saved: "Your date is locked in", public: "Your nickname and date will be visible in any friend challenge you join.",
  results: "See community predictions", community: "The community’s picks", count: "predictions", median: "Middle date", mean: "Average date", mode: "Most picked dates", more: "tied dates", middle: "The central half of predictions falls between", and: "and",
  empty: "Be the first to pick a date.", earlier: "You’re more optimistic than", playersComparison: "of players.", months: "Votes by month", refresh: "Refresh results",
  share: "Share my prediction", download: "Download my card", copied: "Link copied.", copy: "Copy link", challenge: "Challenge your friends", group: "Your friend challenge", join: "Join with my saved date", members: "players", anonymous: "Anonymous", rank: "Rank", difference: "Days away", groupRule: "The closest wins.",
  recovery: "Your private recovery link", createRecovery: "Get my link", recoveryHelp: "Use this link to retrieve your prediction.", recovered: "Your prediction has been restored.", private: "Your private recovery link", closed: "Entries are closed", closedHelp: "An official date has been announced. Results will be settled after publication, even if it is delayed.", actual: "Published in Japan", exact: "exact predictions", error: "Something went wrong. Please try again.", unavailable: "The game is not available yet. Please come back soon.", invalid_date: "Choose a future date within the allowed range.", invalid_nickname: "Enter a nickname of 1–24 characters, without control characters.", verification_required: "Please complete the anti-bot check again.", rate_limited: "Too many requests. Wait a minute and try again.", recovery_invalid: "This private link is invalid or has been replaced.", group_full: "This challenge is full, or you have reached the limit of ten challenges.", not_found: "This challenge or round could not be found.", reload: "Reload the page to enable the anonymous cookie.", vote_first: "Save your prediction first.", shareText: "My prediction for Hunter × Hunter", invitation: "And you? Pick your date.", home: "When do you think the next chapter will arrive?", cta: "Pick your date →", restore: "Copy your private link somewhere safe.",
};
const fr: typeof en = {
  email: "Email (facultatif)", emailHint: "Recevez votre résultat à la sortie du chapitre.", emailAdd: "Recevoir mon pronostic par email", emailPending: "Consultez votre boîte mail pour confirmer votre adresse.", emailConfirmed: "Email confirmé. Vous recevrez les résultats après la publication.", emailConfirm: "Confirmer mon email", emailConfirmTitle: "Recevoir les résultats par email", emailUnsubscribe: "Me désabonner", emailUnsubscribeTitle: "Ne plus recevoir les résultats", emailUnsubscribed: "Vous ne recevrez plus les résultats par email.", emailFailed: "Votre pronostic est enregistré, mais le mail n’a pas pu être préparé.", email_link_invalid: "Ce lien email est invalide ou a expiré.", invalid_email: "Saisissez une adresse email valide.", winners: "Les 10 pronostics les plus proches",

  title: "Vos pronostics", intro: "Quand sortira le prochain chapitre de Hunter × Hunter ? Choisissez une date et défiez vos amis. Sans inscription.",
  chapter: "Chapitre", date: "Date de publication officielle au Japon", nickname: "Pseudo public",
  rule: "Choisissez une date. Les votes ferment dès l’annonce officielle.",
  final: "J’ai compris que ma date ne pourra plus être modifiée.", vote: "Valider ma date", loading: "Chargement…", busy: "Enregistrement…",
  saved: "Votre date est enregistrée", public: "Votre pseudo et votre date seront visibles dans les défis entre amis que vous rejoignez.",
  results: "Voir les pronostics de la communauté", community: "Le choix de la communauté", count: "pronostics", median: "Date médiane", mean: "Date moyenne", mode: "Dates les plus choisies", more: "dates ex æquo", middle: "La moitié centrale des pronostics se situe entre le", and: "et le",
  empty: "Soyez le premier à choisir une date.", earlier: "Vous êtes plus optimiste que", playersComparison: "des joueurs.", months: "Répartition des votes par mois", refresh: "Actualiser les résultats",
  share: "Partager mon pronostic", download: "Télécharger ma carte", copied: "Lien copié.", copy: "Copier le lien", challenge: "Défier mes amis", group: "Votre défi entre amis", join: "Rejoindre avec ma date enregistrée", members: "joueurs", anonymous: "Anonyme", rank: "Rang", difference: "Écart en jours", groupRule: "Le plus proche gagne.",
  recovery: "Votre lien privé de récupération", createRecovery: "Obtenir mon lien", recoveryHelp: "Retrouvez votre pronostic avec ce lien.", recovered: "Votre pronostic a été retrouvé.", private: "Votre lien privé de récupération", closed: "Les pronostics sont fermés", closedHelp: "Une date officielle a été annoncée. Les résultats seront calculés après la publication, même si elle est reportée.", actual: "Publié au Japon le", exact: "pronostics exacts", error: "Une erreur est survenue. Réessayez.", unavailable: "Le jeu n’est pas encore disponible. Revenez bientôt.", invalid_date: "Choisissez une date future dans la plage autorisée.", invalid_nickname: "Saisissez un pseudo de 1 à 24 caractères, sans caractères de contrôle.", verification_required: "Veuillez refaire la vérification anti-robot.", rate_limited: "Trop de demandes. Patientez une minute puis réessayez.", recovery_invalid: "Ce lien privé est invalide ou a été remplacé.", group_full: "Ce défi est complet, ou vous avez atteint la limite de dix défis.", not_found: "Ce défi ou cette manche est introuvable.", reload: "Rechargez la page pour activer le cookie anonyme.", vote_first: "Enregistrez d’abord votre pronostic.", shareText: "Mon pronostic pour Hunter × Hunter", invitation: "Et vous, quelle date choisissez-vous ?", home: "Et vous, vous le voyez sortir quand ?", cta: "Choisir ma date →", restore: "Conservez votre lien privé dans un endroit sûr.",
};

const es: typeof en = {
  "email": "Correo electrónico (opcional)",
  "emailHint": "Recibe tu resultado cuando salga el capítulo.",
  "emailAdd": "Enviarme mi pronóstico",
  "emailPending": "Revisa tu correo para confirmar tu dirección.",
  "emailConfirmed": "Correo confirmado. Recibirás los resultados tras la publicación.",
  "emailConfirm": "Confirmar mi correo",
  "emailConfirmTitle": "Recibir los resultados por correo",
  "emailUnsubscribe": "Dar de baja",
  "emailUnsubscribeTitle": "Dejar de recibir resultados",
  "emailUnsubscribed": "Ya no recibirás los resultados por correo.",
  "emailFailed": "Tu pronóstico está guardado, pero no se pudo preparar el correo.",
  "email_link_invalid": "Este enlace ha caducado o no es válido.",
  "invalid_email": "Introduce un correo válido.",
  "winners": "Los 10 pronósticos más cercanos",
  "title": "Tu pronóstico",
  "intro": "¿Cuándo saldrá el próximo capítulo de Hunter × Hunter? Elige una fecha y reta a tus amigos. Sin cuenta.",
  "chapter": "Capítulo",
  "date": "Fecha oficial de publicación en Japón",
  "nickname": "Apodo público",
  "rule": "Elige una fecha. Los votos se cierran al anunciarse la fecha oficial.",
  "final": "Entiendo que no podré cambiar mi fecha.",
  "vote": "Confirmar mi fecha",
  "loading": "Cargando…",
  "busy": "Guardando…",
  "saved": "Tu fecha está guardada",
  "public": "Tu apodo y tu fecha serán visibles en los retos en los que participes.",
  "results": "Ver los pronósticos",
  "community": "Las fechas de la comunidad",
  "count": "pronósticos",
  "median": "Fecha mediana",
  "mean": "Fecha media",
  "mode": "Fechas más elegidas",
  "more": "fechas empatadas",
  "middle": "La mitad central de los pronósticos está entre",
  "and": "y",
  "empty": "Sé el primero en elegir una fecha.",
  "earlier": "Eres más optimista que",
  "playersComparison": "de los jugadores.",
  "months": "Votos por mes",
  "refresh": "Actualizar resultados",
  "share": "Compartir mi pronóstico",
  "download": "Descargar mi tarjeta",
  "copied": "Enlace copiado.",
  "copy": "Copiar enlace",
  "challenge": "Retar a tus amigos",
  "group": "Tu reto entre amigos",
  "join": "Unirme con mi fecha",
  "members": "jugadores",
  "anonymous": "Anónimo",
  "rank": "Puesto",
  "difference": "Días de diferencia",
  "groupRule": "Gana quien más se acerque.",
  "recovery": "Tu enlace privado de recuperación",
  "createRecovery": "Obtener mi enlace",
  "recoveryHelp": "Recupera tu pronóstico con este enlace.",
  "recovered": "Tu pronóstico se ha recuperado.",
  "private": "Tu enlace privado de recuperación",
  "closed": "Los votos están cerrados",
  "closedHelp": "Ya hay fecha oficial. Los resultados se calcularán tras la publicación.",
  "actual": "Publicado en Japón",
  "exact": "aciertos exactos",
  "error": "Algo salió mal. Inténtalo de nuevo.",
  "unavailable": "El juego aún no está disponible.",
  "invalid_date": "Elige una fecha futura dentro del intervalo permitido.",
  "invalid_nickname": "Introduce un apodo de 1 a 24 caracteres, sin caracteres de control.",
  "verification_required": "Repite la verificación antibots.",
  "rate_limited": "Demasiadas solicitudes. Espera un minuto.",
  "recovery_invalid": "Este enlace privado no es válido o ha sido reemplazado.",
  "group_full": "El reto está lleno o has alcanzado el límite de diez retos.",
  "not_found": "No se encontró este reto o ronda.",
  "reload": "Recarga la página para activar la cookie anónima.",
  "vote_first": "Guarda primero tu pronóstico.",
  "shareText": "Mi pronóstico para Hunter × Hunter",
  "invitation": "¿Y tú? Elige tu fecha.",
  "home": "¿Cuándo crees que llegará el próximo capítulo?",
  "cta": "Elegir mi fecha →",
  "restore": "Guarda tu enlace privado."
};
const pt: typeof en = {
  "email": "Email (opcional)",
  "emailHint": "Receba seu resultado quando o capítulo sair.",
  "emailAdd": "Enviar meu palpite por email",
  "emailPending": "Confira seu email para confirmar o endereço.",
  "emailConfirmed": "Email confirmado. Você receberá os resultados após a publicação.",
  "emailConfirm": "Confirmar meu email",
  "emailConfirmTitle": "Receber os resultados por email",
  "emailUnsubscribe": "Cancelar inscrição",
  "emailUnsubscribeTitle": "Parar de receber resultados",
  "emailUnsubscribed": "Você não receberá mais os resultados por email.",
  "emailFailed": "Seu palpite foi salvo, mas não foi possível preparar o email.",
  "email_link_invalid": "Este link é inválido ou expirou.",
  "invalid_email": "Digite um email válido.",
  "winners": "Os 10 palpites mais próximos",
  "title": "Seu palpite",
  "intro": "Quando sai o próximo capítulo de Hunter × Hunter? Escolha uma data e desafie seus amigos. Sem conta.",
  "chapter": "Capítulo",
  "date": "Data oficial de publicação no Japão",
  "nickname": "Apelido público",
  "rule": "Escolha uma data. Os votos encerram quando a data oficial é anunciada.",
  "final": "Entendo que não poderei mudar minha data.",
  "vote": "Confirmar minha data",
  "loading": "Carregando…",
  "busy": "Salvando…",
  "saved": "Sua data foi salva",
  "public": "Seu apelido e sua data aparecerão nos desafios de que participar.",
  "results": "Ver os palpites",
  "community": "As datas da comunidade",
  "count": "palpites",
  "median": "Data mediana",
  "mean": "Data média",
  "mode": "Datas mais escolhidas",
  "more": "datas empatadas",
  "middle": "A metade central dos palpites está entre",
  "and": "e",
  "empty": "Seja o primeiro a escolher uma data.",
  "earlier": "Você está mais otimista que",
  "playersComparison": "dos jogadores.",
  "months": "Votos por mês",
  "refresh": "Atualizar resultados",
  "share": "Compartilhar meu palpite",
  "download": "Baixar meu cartão",
  "copied": "Link copiado.",
  "copy": "Copiar link",
  "challenge": "Desafiar seus amigos",
  "group": "Seu desafio entre amigos",
  "join": "Entrar com minha data",
  "members": "jogadores",
  "anonymous": "Anônimo",
  "rank": "Posição",
  "difference": "Dias de diferença",
  "groupRule": "Quem chegar mais perto vence.",
  "recovery": "Seu link privado de recuperação",
  "createRecovery": "Obter meu link",
  "recoveryHelp": "Recupere seu palpite com este link.",
  "recovered": "Seu palpite foi recuperado.",
  "private": "Seu link privado de recuperação",
  "closed": "Os votos estão encerrados",
  "closedHelp": "A data oficial foi anunciada. Os resultados serão calculados após a publicação.",
  "actual": "Publicado no Japão",
  "exact": "acertos exatos",
  "error": "Algo deu errado. Tente novamente.",
  "unavailable": "O jogo ainda não está disponível.",
  "invalid_date": "Escolha uma data futura dentro do período permitido.",
  "invalid_nickname": "Digite um apelido de 1 a 24 caracteres, sem caracteres de controle.",
  "verification_required": "Repita a verificação antibot.",
  "rate_limited": "Muitas solicitações. Espere um minuto.",
  "recovery_invalid": "Este link privado é inválido ou foi substituído.",
  "group_full": "O desafio está cheio ou você atingiu o limite de dez desafios.",
  "not_found": "Este desafio ou rodada não foi encontrado.",
  "reload": "Recarregue a página para ativar o cookie anônimo.",
  "vote_first": "Salve seu palpite primeiro.",
  "shareText": "Meu palpite para Hunter × Hunter",
  "invitation": "E você? Escolha sua data.",
  "home": "Quando você acha que o próximo capítulo sai?",
  "cta": "Escolher minha data →",
  "restore": "Guarde seu link privado."
};
const ja: typeof en = {
  "email": "メールアドレス（任意）",
  "emailHint": "掲載後に結果をメールでお届けします。",
  "emailAdd": "予想をメールで受け取る",
  "emailPending": "メールを開いてアドレスを確認してください。",
  "emailConfirmed": "メールアドレスを確認しました。公開後に結果をお届けします。",
  "emailConfirm": "メールアドレスを確認",
  "emailConfirmTitle": "結果をメールで受け取る",
  "emailUnsubscribe": "配信停止",
  "emailUnsubscribeTitle": "結果メールの配信停止",
  "emailUnsubscribed": "結果メールの配信を停止しました。",
  "emailFailed": "予想は保存されましたが、メールを準備できませんでした。",
  "email_link_invalid": "このメールリンクは無効か期限切れです。",
  "invalid_email": "有効なメールアドレスを入力してください。",
  "winners": "最も近かった予想トップ10",
  "title": "あなたの予想",
  "intro": "Hunter × Hunterの次の話はいつ公開される？日付を選んで友達と勝負しよう。アカウント不要。",
  "chapter": "話数",
  "date": "日本での公式公開日",
  "nickname": "公開ニックネーム",
  "rule": "日付を選んでください。公式日程の発表で投票を締め切ります。",
  "final": "日付を変更できないことを理解しました。",
  "vote": "この日付で投票",
  "loading": "読み込み中…",
  "busy": "保存中…",
  "saved": "予想を保存しました",
  "public": "参加する友達チャレンジにニックネームと日付が表示されます。",
  "results": "みんなの予想を見る",
  "community": "みんなの予想",
  "count": "件の予想",
  "median": "中央値の日付",
  "mean": "平均の日付",
  "mode": "人気の予想日",
  "more": "同票の日付",
  "middle": "予想の中央50%の範囲：",
  "and": "〜",
  "empty": "最初の予想を投稿しよう。",
  "earlier": "あなたより遅い日付を予想した人：",
  "playersComparison": "",
  "months": "月別の投票数",
  "refresh": "結果を更新",
  "share": "予想をシェア",
  "download": "カードを保存",
  "copied": "リンクをコピーしました。",
  "copy": "リンクをコピー",
  "challenge": "友達と勝負",
  "group": "友達チャレンジ",
  "join": "保存した日付で参加",
  "members": "人",
  "anonymous": "匿名",
  "rank": "順位",
  "difference": "日数差",
  "groupRule": "一番近い人の勝ち。",
  "recovery": "予想を復元する専用リンク",
  "createRecovery": "リンクを取得",
  "recoveryHelp": "このリンクで予想を復元できます。",
  "recovered": "予想を復元しました。",
  "private": "予想を復元する専用リンク",
  "closed": "投票は締め切りました",
  "closedHelp": "公式日程が発表されました。公開後に結果を集計します。",
  "actual": "日本での公開日",
  "exact": "件の的中",
  "error": "エラーが発生しました。もう一度お試しください。",
  "unavailable": "ゲームはまだ利用できません。",
  "invalid_date": "選択可能な範囲で未来の日付を選んでください。",
  "invalid_nickname": "ニックネームは1〜24文字で入力してください。制御文字は使えません。",
  "verification_required": "ボット対策の認証をやり直してください。",
  "rate_limited": "リクエストが多すぎます。1分待ってください。",
  "recovery_invalid": "この専用リンクは無効か更新されています。",
  "group_full": "定員に達したか、参加上限の10チャレンジに達しました。",
  "not_found": "チャレンジまたはラウンドが見つかりません。",
  "reload": "ページを再読み込みして匿名Cookieを有効にしてください。",
  "vote_first": "先に予想を保存してください。",
  "shareText": "Hunter × Hunterの公開日予想",
  "invitation": "あなたはいつだと思う？",
  "home": "次の話はいつ公開されると思う？",
  "cta": "日付を選ぶ →",
  "restore": "専用リンクを保存してください。"
};
const zh: typeof en = {
  "email": "电子邮箱（选填）",
  "emailHint": "章节发布后，通过邮件接收你的结果。",
  "emailAdd": "通过邮件收取预测",
  "emailPending": "请查看邮件并确认邮箱地址。",
  "emailConfirmed": "邮箱已确认，章节发布后会收到结果。",
  "emailConfirm": "确认邮箱",
  "emailConfirmTitle": "通过邮件收取结果",
  "emailUnsubscribe": "取消订阅",
  "emailUnsubscribeTitle": "停止接收结果邮件",
  "emailUnsubscribed": "你将不再收到结果邮件。",
  "emailFailed": "预测已保存，但邮件暂时无法发送。",
  "email_link_invalid": "邮件链接无效或已过期。",
  "invalid_email": "请输入有效的邮箱地址。",
  "winners": "最接近的10个预测",
  "title": "你的预测",
  "intro": "Hunter × Hunter下一话什么时候发布？选个日期，和朋友比一比。无需账号。",
  "chapter": "话数",
  "date": "日本官方发布日期",
  "nickname": "公开昵称",
  "rule": "请选择日期。官方日期公布后停止投票。",
  "final": "我已了解日期无法修改。",
  "vote": "提交预测",
  "loading": "加载中…",
  "busy": "保存中…",
  "saved": "预测已保存",
  "public": "你的昵称和日期会显示在你参加的好友挑战中。",
  "results": "查看大家的预测",
  "community": "大家的预测",
  "count": "个预测",
  "median": "中位日期",
  "mean": "平均日期",
  "mode": "最热门的日期",
  "more": "个并列日期",
  "middle": "中间50%的预测日期介于",
  "and": "至",
  "empty": "来做第一个预测的人吧。",
  "earlier": "你比",
  "playersComparison": "的玩家更乐观。",
  "months": "每月票数",
  "refresh": "刷新结果",
  "share": "分享预测",
  "download": "下载卡片",
  "copied": "链接已复制。",
  "copy": "复制链接",
  "challenge": "挑战好友",
  "group": "好友挑战",
  "join": "使用已选日期加入",
  "members": "位玩家",
  "anonymous": "匿名",
  "rank": "排名",
  "difference": "相差天数",
  "groupRule": "最接近的人获胜。",
  "recovery": "你的私人恢复链接",
  "createRecovery": "获取链接",
  "recoveryHelp": "用此链接找回你的预测。",
  "recovered": "已找回你的预测。",
  "private": "你的私人恢复链接",
  "closed": "投票已结束",
  "closedHelp": "官方日期已公布，章节发布后将计算结果。",
  "actual": "日本发布日期",
  "exact": "个完全命中的预测",
  "error": "出错了，请重试。",
  "unavailable": "游戏暂未开放。",
  "invalid_date": "请选择允许范围内的未来日期。",
  "invalid_nickname": "请输入1至24个字符的昵称，不含控制字符。",
  "verification_required": "请重新完成人机验证。",
  "rate_limited": "请求过多，请稍等一分钟。",
  "recovery_invalid": "私人链接无效或已被替换。",
  "group_full": "挑战已满，或你已达到10个挑战的上限。",
  "not_found": "找不到此挑战或轮次。",
  "reload": "请刷新页面以启用匿名Cookie。",
  "vote_first": "请先保存你的预测。",
  "shareText": "我对Hunter × Hunter的预测",
  "invitation": "你呢？选个日期吧。",
  "home": "你觉得下一话什么时候发布？",
  "cta": "选择日期 →",
  "restore": "请保存你的私人链接。"
};
const ar: typeof en = {
  "email": "البريد الإلكتروني (اختياري)",
  "emailHint": "ستصلك نتيجتك عند صدور الفصل.",
  "emailAdd": "إرسال توقعي بالبريد",
  "emailPending": "افتح بريدك لتأكيد عنوانك.",
  "emailConfirmed": "تم تأكيد البريد. ستصلك النتائج بعد النشر.",
  "emailConfirm": "تأكيد بريدي",
  "emailConfirmTitle": "استلام النتائج بالبريد",
  "emailUnsubscribe": "إلغاء الاشتراك",
  "emailUnsubscribeTitle": "إيقاف رسائل النتائج",
  "emailUnsubscribed": "لن تصلك رسائل النتائج بعد الآن.",
  "emailFailed": "تم حفظ توقعك، لكن تعذر تجهيز الرسالة.",
  "email_link_invalid": "رابط البريد غير صالح أو انتهت صلاحيته.",
  "invalid_email": "أدخل بريدًا إلكترونيًا صالحًا.",
  "winners": "أقرب 10 توقعات",
  "title": "توقعك",
  "intro": "متى يصدر الفصل القادم من Hunter × Hunter؟ اختر تاريخًا وتحدَّ أصدقاءك. لا حاجة إلى حساب.",
  "chapter": "الفصل",
  "date": "موعد النشر الرسمي في اليابان",
  "nickname": "الاسم المستعار العلني",
  "rule": "اختر تاريخًا. يُغلق التصويت عند إعلان الموعد الرسمي.",
  "final": "أفهم أنني لن أتمكن من تغيير التاريخ.",
  "vote": "تأكيد توقعي",
  "loading": "جارٍ التحميل…",
  "busy": "جارٍ الحفظ…",
  "saved": "تم حفظ توقعك",
  "public": "سيظهر اسمك وتاريخك في تحديات الأصدقاء التي تنضم إليها.",
  "results": "عرض توقعات المشاركين",
  "community": "توقعات المشاركين",
  "count": "توقعات",
  "median": "التاريخ الوسيط",
  "mean": "متوسط التواريخ",
  "mode": "التواريخ الأكثر اختيارًا",
  "more": "تواريخ متعادلة",
  "middle": "يقع النصف الأوسط من التوقعات بين",
  "and": "و",
  "empty": "كن أول من يختار تاريخًا.",
  "earlier": "أنت أكثر تفاؤلًا من",
  "playersComparison": "من المشاركين.",
  "months": "الأصوات حسب الشهر",
  "refresh": "تحديث النتائج",
  "share": "مشاركة توقعي",
  "download": "تنزيل بطاقتي",
  "copied": "تم نسخ الرابط.",
  "copy": "نسخ الرابط",
  "challenge": "تحدَّ أصدقاءك",
  "group": "تحدي الأصدقاء",
  "join": "الانضمام بتاريخي المحفوظ",
  "members": "مشاركين",
  "anonymous": "مجهول",
  "rank": "الترتيب",
  "difference": "الفارق بالأيام",
  "groupRule": "الأقرب يفوز.",
  "recovery": "رابطك الخاص لاستعادة التوقع",
  "createRecovery": "الحصول على الرابط",
  "recoveryHelp": "استعد توقعك عبر هذا الرابط.",
  "recovered": "تمت استعادة توقعك.",
  "private": "رابطك الخاص لاستعادة التوقع",
  "closed": "انتهى التصويت",
  "closedHelp": "أُعلن الموعد الرسمي. ستُحسب النتائج بعد النشر.",
  "actual": "تاريخ النشر في اليابان",
  "exact": "توقعات مطابقة تمامًا",
  "error": "حدث خطأ. حاول مجددًا.",
  "unavailable": "اللعبة غير متاحة بعد.",
  "invalid_date": "اختر تاريخًا مستقبليًا ضمن الفترة المسموحة.",
  "invalid_nickname": "أدخل اسمًا مستعارًا من حرف واحد إلى 24 حرفًا، دون محارف تحكم.",
  "verification_required": "أعد التحقق من أنك لست روبوتًا.",
  "rate_limited": "طلبات كثيرة. انتظر دقيقة ثم حاول مجددًا.",
  "recovery_invalid": "هذا الرابط الخاص غير صالح أو تم استبداله.",
  "group_full": "التحدي ممتلئ أو بلغت حد عشرة تحديات.",
  "not_found": "لم يتم العثور على هذا التحدي أو الجولة.",
  "reload": "أعد تحميل الصفحة لتفعيل ملف الارتباط المجهول.",
  "vote_first": "احفظ توقعك أولًا.",
  "shareText": "توقعي لموعد Hunter × Hunter",
  "invitation": "وأنت؟ اختر تاريخك.",
  "home": "متى تتوقع صدور الفصل القادم؟",
  "cta": "اختر تاريخك ←",
  "restore": "احتفظ برابطك الخاص."
};

const copies = {
  en: { ...en, ...gameFlowCopy.en }, fr: { ...fr, ...gameFlowCopy.fr },
  es: { ...es, ...gameFlowCopy.es }, pt: { ...pt, ...gameFlowCopy.pt },
  ja: { ...ja, ...gameFlowCopy.ja }, zh: { ...zh, ...gameFlowCopy.zh },
  ar: { ...ar, ...gameFlowCopy.ar },
};
export const gameCopy = (locale: Locale) => copies[locale];
